<a href="https://colab.research.google.com/github/slugmilk/Study_Data-Analysis/blob/main/2_%ED%8C%90%EB%8B%A4%EC%8A%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. 판다스(Pandas)**
* 데이터 분석을 위한 파이썬 라이브러리 중 하나로, 표 형태의 데이터나 다양한 형태의 데이터를 쉽게 처리하고 분석
* 데이터프레임(DataFrame)이라는 자료구조를 제공

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
import pandas as pd

# **2. Series와 DataFrame**

### 2-1. Series
* Series는 1차원 배열과 같은 자료구조로 하나의 열을 나타냄
* Series의 각 요소는 인덱스(index)와 값(value)으로 구성되어 있음
* 값은 넘파이의 ndarray 기반으로 저장됨
* Series는 다양한 데이터 타입을 가질 수 있으며, 정수, 실수, 문자열 등 다양한 형태의 데이터를 담을 수 있음

In [ ]:
idx = ['유민콩', '정현콩', '수현콩', '유현콩', '유선콩']
data = [100, 95, 80, 55, 60]

In [ ]:
# pd.Series(데이터, 인덱스(생략가능) ...)
pd.Series(data)

0    100
1     95
2     80
3     55
4     60
dtype: int64

In [ ]:
se1 = pd.Series(data, idx)
se1

유민콩    100
정현콩     95
수현콩     80
유현콩     55
유선콩     60
dtype: int64

In [ ]:
print(se1.index)
print(se1.values)

Index(['유민콩', '정현콩', '수현콩', '유현콩', '유선콩'], dtype='object')
[100  95  80  55  60]

### 2-2. DataFrame
* 데이터프레임은 판다스 라이브러리에서 제공하는 중요하고 강력한 데이터 구조로, 엑셀과 유사한 2차원의 테이블 형태 데이터를 다룸
* 데이터프레임의 요소는 인덱스(index), 열(column), 값(value)
* 데이터프레임은 행과 열로 이루어져 있으며, 각 열은 다양한 데이터 타입을 가질 수 있음
* 값은 넘파이의 ndarray 기반으로 저장

In [ ]:
data = [[67, 93, 91],
        [75, 68, 96],
        [87, 81, 82],
        [62, 70, 75],
        [98, 56, 87]]

idx = ['유민콩', '정현콩', '수현콩', '유현콩', '유선콩']
col = ['국어', '영어', '수학']

In [ ]:
# pd.DataFrame(데이터, 인덱스, 컬럼, ...)
pd.DataFrame(data)

    0   1   2
0  67  93  91
1  75  68  96
2  87  81  82
3  62  70  75
4  98  56  87

In [ ]:
pd.DataFrame(data, idx)

      0   1   2
유민콩  67  93  91
정현콩  75  68  96
수현콩  87  81  82
유현콩  62  70  75
유선콩  98  56  87

In [ ]:
pd.DataFrame(data, idx, col)

     국어  영어  수학
유민콩  67  93  91
정현콩  75  68  96
수현콩  87  81  82
유현콩  62  70  75
유선콩  98  56  87

In [ ]:
df = pd.DataFrame(index = idx, columns = col, data = data)
df

     국어  영어  수학
유민콩  67  93  91
정현콩  75  68  96
수현콩  87  81  82
유현콩  62  70  75
유선콩  98  56  87

In [ ]:
print(df.index)
print(df.columns)
print(df.values)

Index(['유민콩', '정현콩', '수현콩', '유현콩', '유선콩'], dtype='object')
Index(['국어', '영어', '수학'], dtype='object')
[[67 93 91]
 [75 68 96]
 [87 81 82]
 [62 70 75]
 [98 56 87]]

### 2-3. 딕셔너리를 사용하여 데이터프레임 생성하기

In [ ]:
dic = {
    '국어':[67, 75, 87, 62, 98],
    '영어':[93, 68, 81, 70, 56],
    '수학':[91, 96, 82, 75, 87]
}

In [ ]:
df = pd.DataFrame(data=dic, index=idx)
df

     국어  영어  수학
유민콩  67  93  91
정현콩  75  68  96
수현콩  87  81  82
유현콩  62  70  75
유선콩  98  56  87

# **3. CSV 파일 읽어오기**
* csv(Comma Seperated Value)의 약자로, 데이터를 쉼표로 구분한 파일

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/컴퓨터비전_시즌2/3. 데이터 분석/Data/idol.csv')
df

      이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587

In [ ]:
type(df)

pandas.core.frame.DataFrame

# **4. 데이터프레임 기본정보 알아보기**

In [ ]:
# info(): 행(row), 열(colums)의 기본적인 정보와 데이터 타입을 반환
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   이름       20 non-null     object
 1   그룹       20 non-null     object
 2   소속사      19 non-null     object
 3   성별       20 non-null     object
 4   생년월일     20 non-null     object
 5   키        19 non-null     float64
 6   혈액형      19 non-null     object
 7   브랜드평판지수  20 non-null     int64
dtypes: float64(1), int64(1), object(6)
memory usage: 1.4+ KB

In [ ]:
# 컬럼명 변경하기
print(df.columns)

Index(['이름', '그룹', '소속사', '성별', '생년월일', '키', '혈액형', '브랜드평판지수'], dtype='object')

In [ ]:
new_columns = ['name', 'group', 'company', 'gender', 'birthday', 'height', 'blood', 'brand']
df.columns = new_columns
df

    name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [ ]:
# describe(): 통계 정보를 반환
df.describe()

           height         brand
count   19.000000  2.000000e+01
mean   170.536842  2.700190e+06
std      7.225204  1.381919e+06
min    161.000000  1.680587e+06
25%    164.750000  1.887423e+06
50%    168.000000  2.074682e+06
75%    179.000000  2.623465e+06
max    182.000000  6.267302e+06

In [ ]:
df.describe(include=object) # top:최빈값  freq: 최빈값의 빈도

       name  group company gender    birthday blood
count    20     20      19     20          20    19
unique   20      6       5      2          20     4
top      지민  방탄소년단     빅히트     여자  1995-10-13     A
freq      1      5       7     13           1    11

In [ ]:
# 원하는 개수의 데이터 보기
df.head()

  name  group company gender    birthday  height blood    brand
0   지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1   정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2   민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3   하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4    뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048

In [ ]:
df.head(3) # 3개

  name  group company gender    birthday  height blood    brand
0   지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1   정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2   민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081

In [ ]:
df.tail() # 하위 5개

    name  group company gender    birthday  height blood    brand
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [ ]:
# 정렬
df.sort_index() # index로 오름차순 정렬(기본값)

    name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [ ]:
df.sort_index(ascending=False) # index로 내림차순 정렬

    name  group company gender    birthday  height blood    brand
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302

In [ ]:
df.sort_values(by='height') # 키로 오름차순 정렬

    name  group company gender    birthday  height blood    brand
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866

In [ ]:
df.sort_values(by='height', ascending=False) # 키로 내림차순 정렬

    name  group company gender    birthday  height blood    brand
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866

In [ ]:
df.sort_values(by='height', ascending=False, na_position='first') # nan값 젤 위로 올리기

    name  group company gender    birthday  height blood    brand
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767

In [ ]:
# 1차 저렬: 키(내림차순), 2차 정렬: 브랜드(내림차순)
df.sort_values(by=['height', 'brand'], ascending=[False, False])

    name  group company gender    birthday  height blood    brand
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866

# **데이터 다루기**

In [ ]:
df.head()

  name  group company gender    birthday  height blood    brand
0   지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1   정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2   민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3   하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4    뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048

In [ ]:
df['blood']

0       A
1       A
2       A
3       O
4      AB
5     NaN
6       O
7       A
8       B
9       A
10      A
11      B
12      A
13      A
14      B
15      B
16      A
17      A
18      A
19      O
Name: blood, dtype: object

In [ ]:
type(df['blood'])

pandas.core.series.Series

In [ ]:
df.blood

0       A
1       A
2       A
3       O
4      AB
5     NaN
6       O
7       A
8       B
9       A
10      A
11      B
12      A
13      A
14      B
15      B
16      A
17      A
18      A
19      O
Name: blood, dtype: object

In [ ]:
df.head(3)

  name  group company gender    birthday  height blood    brand
0   지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1   정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2   민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081

In [ ]:
df[:3]

  name  group company gender    birthday  height blood    brand
0   지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1   정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2   민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081

In [ ]:
# loc 인덱싱: 컬럼 인덱싱, 행과 열 모두 인덱싱과 슬라이싱이 가능
df.loc[:, 'name'] # 행 다 가져오고 이름 열만

0       지민
1       정국
2       민지
3       하니
4        뷔
5      다니엘
6       혜인
7       지수
8       해린
9       태연
10      RM
11      제니
12     옹성우
13      리사
14      로제
15      윤아
16      조이
17      슬기
18    강다니엘
19       진
Name: name, dtype: object

In [ ]:
df.loc[2:5, 'name'] # 2행부터 5행(포함)

2     민지
3     하니
4      뷔
5    다니엘
Name: name, dtype: object

In [ ]:
df.loc[2:5, ['name', 'gender', 'height']] # 2행부터 5행(포함)

  name gender  height
2   민지     여자   169.0
3   하니     여자   161.7
4    뷔     남자   179.0
5  다니엘     여자   165.0

In [ ]:
df.loc[[2,5], 'name':'gender']

  name group company gender
2   민지   뉴진스     어도어     여자
5  다니엘   뉴진스     어도어     여자

In [ ]:
# iloc 인덱싱: index로 인덱싱. 행과 열 모두 인덱싱과 슬라이싱이 가능
df.iloc[:, 0]

0       지민
1       정국
2       민지
3       하니
4        뷔
5      다니엘
6       혜인
7       지수
8       해린
9       태연
10      RM
11      제니
12     옹성우
13      리사
14      로제
15      윤아
16      조이
17      슬기
18    강다니엘
19       진
Name: name, dtype: object

In [ ]:
df.iloc[:, [0,2]]

    name company
0     지민     빅히트
1     정국     빅히트
2     민지     어도어
3     하니     어도어
4      뷔     빅히트
5    다니엘     어도어
6     혜인     어도어
7     지수     와이지
8     해린     어도어
9     태연     에스엠
10    RM     빅히트
11    제니     와이지
12   옹성우    판타지오
13    리사     와이지
14    로제     와이지
15    윤아     에스엠
16    조이     빅히트
17    슬기     빅히트
18  강다니엘     NaN
19     진     빅히트

In [ ]:
df.iloc[:, 0:2] # 2번 컬럼 포함 X

    name  group
0     지민  방탄소년단
1     정국  방탄소년단
2     민지    뉴진스
3     하니    뉴진스
4      뷔  방탄소년단
5    다니엘    뉴진스
6     혜인    뉴진스
7     지수   블랙핑크
8     해린    뉴진스
9     태연   소녀시대
10    RM  방탄소년단
11    제니   블랙핑크
12   옹성우    워너원
13    리사   블랙핑크
14    로제   블랙핑크
15    윤아   소녀시대
16    조이   레드벨벳
17    슬기   레드벨벳
18  강다니엘    워너원
19     진  방탄소년단

In [ ]:
df.iloc[1:5, 0:2]

  name  group
1   정국  방탄소년단
2   민지    뉴진스
3   하니    뉴진스
4    뷔  방탄소년단

In [ ]:
df['height'] >= 180

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
Name: height, dtype: bool

In [ ]:
df[df['height'] >= 180]

    name  group company gender    birthday  height blood    brand
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444

In [ ]:
df[df['height'] >= 180]['name'] # 앞 뒤 순서 바꿀 수 있음

10      RM
18    강다니엘
Name: name, dtype: object

In [ ]:
df[df['height'] >= 180][['name', 'gender']]

    name gender
10    RM     남자
18  강다니엘     남자

### 문제
* 키가 170cm 이상인 연예인의 이름, 성별, 브랜드 데이터를 출력
* 단, loc를 사용

In [ ]:
df.loc[df['height'] >= 170, ['name', 'gender', 'brand']]

    name gender    brand
0     지민     남자  6267302
1     정국     남자  5805844
4      뷔     남자  3470048
6     혜인     여자  2301785
10    RM     남자  2069499
12   옹성우     남자  1954327
18  강다니엘     남자  1706444
19     진     남자  1680587

In [ ]:
# isin(): 정의한 리스트에 있는 데이터를 불린으로 반환

In [ ]:
company = ['빅히트', '어도어']
df['company'].isin(company)

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7     False
8      True
9     False
10     True
11    False
12    False
13    False
14    False
15    False
16     True
17     True
18    False
19     True
Name: company, dtype: bool

In [ ]:
df[df['company'].isin(company)]

   name  group company gender    birthday  height blood    brand
0    지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1    정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2    민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3    하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4     뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5   다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6    혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
8    해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
10   RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
16   조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17   슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
19    진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

# **6. 결측값(Null, NaN)**
* 비어있는 값, 판다스에서는 NaN(Not a number)로 표기한 것은 모두 결측값으로 취급

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      20 non-null     object
 1   group     20 non-null     object
 2   company   19 non-null     object
 3   gender    20 non-null     object
 4   birthday  20 non-null     object
 5   height    19 non-null     float64
 6   blood     19 non-null     object
 7   brand     20 non-null     int64
dtypes: float64(1), int64(1), object(6)
memory usage: 1.4+ KB

In [ ]:
df.isna()

     name  group  company  gender  birthday  height  blood  brand
0   False  False    False   False     False   False  False  False
1   False  False    False   False     False   False  False  False
2   False  False    False   False     False   False  False  False
3   False  False    False   False     False   False  False  False
4   False  False    False   False     False   False  False  False
5   False  False    False   False     False   False   True  False
6   False  False    False   False     False   False  False  False
7   False  False    False   False     False   False  False  False
8   False  False    False   False     False   False  False  False
9   False  False    False   False     False    True  False  False
10  False  False    False   False     False   False  False  False
11  False  False    False   False     False   False  False  False
12  False  False    False   False     False   False  False  False
13  False  False    False   False     False   False  False  False
14  False  False    False   False     False   False  False  False
15  False  False    False   False     False   False  False  False
16  False  False    False   False     False   False  False  False
17  False  False    False   False     False   False  False  False
18  False  False     True   False     False   False  False  False
19  False  False    False   False     False   False  False  False

In [ ]:
df[df['height'].isna()]

  name group company gender    birthday  height blood    brand
9   태연  소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866

In [ ]:
df[df['height'].notnull()]

    name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

### 문제
* 회사가 존재하는 연예인의 이름, 회사, 그룹, 성별의 데이터를 출력
* 단, loc를 사용

In [ ]:
df.loc[df['company'].notnull(), ['name', 'company', 'group', 'gender']]

   name company  group gender
0    지민     빅히트  방탄소년단     남자
1    정국     빅히트  방탄소년단     남자
2    민지     어도어    뉴진스     여자
3    하니     어도어    뉴진스     여자
4     뷔     빅히트  방탄소년단     남자
5   다니엘     어도어    뉴진스     여자
6    혜인     어도어    뉴진스     여자
7    지수     와이지   블랙핑크     여자
8    해린     어도어    뉴진스     여자
9    태연     에스엠   소녀시대     여자
10   RM     빅히트  방탄소년단     남자
11   제니     와이지   블랙핑크     여자
12  옹성우    판타지오    워너원     남자
13   리사     와이지   블랙핑크     여자
14   로제     와이지   블랙핑크     여자
15   윤아     에스엠   소녀시대     여자
16   조이     빅히트   레드벨벳     여자
17   슬기     빅히트   레드벨벳     여자
19    진     빅히트  방탄소년단     남자

In [ ]:
# fillna(): 결측값을 채워주는 함수
df['height'].fillna(0) # df['height'].fillna(0, inplace=True)

0     174.0
1     179.0
2     169.0
3     161.7
4     179.0
5     165.0
6     170.0
7     162.0
8     164.5
9       0.0
10    181.0
11    163.0
12    179.0
13    167.0
14    168.0
15    168.0
16    168.0
17    161.0
18    182.0
19    179.0
Name: height, dtype: float64

In [ ]:
df_copy = df.copy()
df_copy

    name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [ ]:
height = df_copy['height'].mean()
height

170.53684210526316

In [ ]:
df_copy['height'] = df_copy['height'].fillna(height)
df_copy

    name  group company gender    birthday      height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13  174.000000     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01  179.000000     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07  169.000000     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06  161.700000     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30  179.000000    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11  165.000000   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21  170.000000     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03  162.000000     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15  164.500000     B  2173376
9     태연   소녀시대     에스엠     여자  1989-03-09  170.536842     A  2079866
10    RM  방탄소년단     빅히트     남자  1994-09-12  181.000000     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16  163.000000     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25  179.000000     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27  167.000000     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11  168.000000     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30  168.000000     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03  168.000000     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10  161.000000     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10  182.000000     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04  179.000000     O  1680587

In [ ]:
df_copy = df.copy()
df_copy

    name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [ ]:
height = df_copy['height'].median() # 50% 값, 중위
height

168.0

In [ ]:
df_copy['height'] = df_copy['height'].fillna(height)
df_copy

    name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
9     태연   소녀시대     에스엠     여자  1989-03-09   168.0     A  2079866
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [ ]:
df_copy = df.copy()
df_copy

    name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [ ]:
# dropna(): 결측값이 있는 행 또는 열 제거. 결측값이 한 개라도 있는 경우 삭제
df_copy.dropna() # axis=0: 행 삭제. 기본값

   name  group company gender    birthday  height blood    brand
0    지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1    정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2    민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3    하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4     뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
6    혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7    지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8    해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
10   RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11   제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12  옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13   리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14   로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15   윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16   조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17   슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
19    진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [ ]:
df_copy.dropna(axis=1) # 결측값 있는 열 제거

    name  group gender    birthday    brand
0     지민  방탄소년단     남자  1995-10-13  6267302
1     정국  방탄소년단     남자  1997-09-01  5805844
2     민지    뉴진스     여자  2004-05-07  4437081
3     하니    뉴진스     여자  2004-10-06  4161153
4      뷔  방탄소년단     남자  1995-12-30  3470048
5    다니엘    뉴진스     여자  2005-04-11  2341271
6     혜인    뉴진스     여자  2008-04-21  2301785
7     지수   블랙핑크     여자  1995-01-03  2227460
8     해린    뉴진스     여자  2006-05-15  2173376
9     태연   소녀시대     여자  1989-03-09  2079866
10    RM  방탄소년단     남자  1994-09-12  2069499
11    제니   블랙핑크     여자  1996-01-16  2069250
12   옹성우    워너원     남자  1995-08-25  1954327
13    리사   블랙핑크     여자  1997-03-27  1912800
14    로제   블랙핑크     여자  1997-02-11  1888132
15    윤아   소녀시대     여자  1990-05-30  1885297
16    조이   레드벨벳     여자  1996-09-03  1830514
17    슬기   레드벨벳     여자  1994-02-10  1741767
18  강다니엘    워너원     남자  1996-12-10  1706444
19     진  방탄소년단     남자  1992-12-04  1680587

# **7. 행, 열 추가 및 삭제하기**
* 행을 추가할 때 dict 형태의 데이터를 만들고 append() 메서드를 사용하ㅕ 데이터를 추가
* ignore_inex = True 옵션을 추가해야 에러가 발생하지 않음

In [ ]:
df_copy = df.copy()
df_copy

    name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [ ]:
dic = {
    'name':'유민콩',
    'group':'콩',
    'company':'우유조아',
    'gender':'여자',
    'birthday':'2020-02-02',
    'height':140,
    'blood':'A',
    'brand':1234567
}

In [ ]:
# concat(): 데이터를 합침. axis=0 (기본)
df = pd.concat([df_copy, pd.DataFrame(dic, index=[0])], ignore_index=True)
df

    name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587
20   유민콩      콩    우유조아     여자  2020-02-02   140.0     A  1234567

### 문제
* nation이라는 열을 추가하고, nation에 모든 데이터는 '대한민국'이라고 저장
* 단, '유민콩'의 국적을 미국으로 변경하고 loc를 사용하여 출력

In [ ]:
df['nation'] = '대한민국'
df

    name  group company gender    birthday  height blood    brand nation
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302   대한민국
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844   대한민국
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081   대한민국
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153   대한민국
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048   대한민국
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271   대한민국
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785   대한민국
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460   대한민국
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376   대한민국
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866   대한민국
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499   대한민국
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250   대한민국
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327   대한민국
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800   대한민국
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132   대한민국
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297   대한민국
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514   대한민국
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767   대한민국
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444   대한민국
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587   대한민국
20   유민콩      콩    우유조아     여자  2020-02-02   140.0     A  1234567   대한민국

In [ ]:
df.loc[df['name'] == '유민콩', 'nation'] = '미국'

In [ ]:
df

    name  group company gender    birthday  height blood    brand nation
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302   대한민국
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844   대한민국
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081   대한민국
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153   대한민국
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048   대한민국
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271   대한민국
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785   대한민국
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460   대한민국
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376   대한민국
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866   대한민국
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499   대한민국
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250   대한민국
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327   대한민국
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800   대한민국
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132   대한민국
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297   대한민국
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514   대한민국
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767   대한민국
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444   대한민국
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587   대한민국
20   유민콩      콩    우유조아     여자  2020-02-02   140.0     A  1234567     미국

In [ ]:
# 행 제거
df.drop(20, axis=0) # 20번 행 제거

    name  group company gender    birthday  height blood    brand nation
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302   대한민국
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844   대한민국
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081   대한민국
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153   대한민국
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048   대한민국
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271   대한민국
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785   대한민국
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460   대한민국
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376   대한민국
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866   대한민국
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499   대한민국
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250   대한민국
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327   대한민국
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800   대한민국
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132   대한민국
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297   대한민국
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514   대한민국
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767   대한민국
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444   대한민국
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587   대한민국

In [ ]:
df.tail() # 제거는 안됨

    name  group company gender    birthday  height blood    brand nation
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514   대한민국
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767   대한민국
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444   대한민국
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587   대한민국
20   유민콩      콩    우유조아     여자  2020-02-02   140.0     A  1234567     미국

In [ ]:
df.drop([1, 3, 5, 7, 20], axis=0)
df

    name  group company gender    birthday  height blood    brand nation
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302   대한민국
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844   대한민국
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081   대한민국
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153   대한민국
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048   대한민국
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271   대한민국
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785   대한민국
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460   대한민국
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376   대한민국
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866   대한민국
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499   대한민국
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250   대한민국
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327   대한민국
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800   대한민국
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132   대한민국
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297   대한민국
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514   대한민국
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767   대한민국
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444   대한민국
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587   대한민국
20   유민콩      콩    우유조아     여자  2020-02-02   140.0     A  1234567     미국

In [ ]:
df.drop('nation', axis=1)
df

    name  group company gender    birthday  height blood    brand nation
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302   대한민국
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844   대한민국
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081   대한민국
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153   대한민국
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048   대한민국
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271   대한민국
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785   대한민국
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460   대한민국
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376   대한민국
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866   대한민국
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499   대한민국
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250   대한민국
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327   대한민국
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800   대한민국
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132   대한민국
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297   대한민국
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514   대한민국
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767   대한민국
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444   대한민국
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587   대한민국
20   유민콩      콩    우유조아     여자  2020-02-02   140.0     A  1234567     미국

In [ ]:
df.drop(['group', 'nation'], axis=1)
df

    name  group company gender    birthday  height blood    brand nation
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302   대한민국
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844   대한민국
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081   대한민국
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153   대한민국
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048   대한민국
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271   대한민국
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785   대한민국
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460   대한민국
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376   대한민국
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866   대한민국
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499   대한민국
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250   대한민국
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327   대한민국
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800   대한민국
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132   대한민국
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297   대한민국
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514   대한민국
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767   대한민국
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444   대한민국
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587   대한민국
20   유민콩      콩    우유조아     여자  2020-02-02   140.0     A  1234567     미국

# **8. 통계함수**

In [ ]:
df.describe()

           height         brand
count   20.000000  2.100000e+01
mean   169.010000  2.630399e+06
std      9.802089  1.384378e+06
min    140.000000  1.234567e+06
25%    164.125000  1.885297e+06
50%    168.000000  2.069499e+06
75%    179.000000  2.341271e+06
max    182.000000  6.267302e+06

In [ ]:
df['height'].sum() # 합계

3380.2

In [ ]:
df['height'].count() # 결측 제외 개수

20

In [ ]:
df['height'].mean() # 평균

169.01

In [ ]:
df['height'].median() # 중위

168.0

In [ ]:
df['height'].max() # 최대값

182.0

In [ ]:
df['height'].min() # 최소값

140.0

In [ ]:
df['height'].var() # 분산

96.08094736842105

In [ ]:
df['height'].std() # 표준편차

9.802088928816197

# **9. 그룹**

In [ ]:
# groupby(): 데이터를 그룹으로 묶어서 분석할 때 사용
df.groupby('group')

In [ ]:
# 그룹을 맺으면 통계함수를 사용할 수 있음
df.groupby('group').count()

       name  company  gender  birthday  height  blood  brand  nation
group
뉴진스       5        5       5         5       5      4      5       5
레드벨벳      2        2       2         2       2      2      2       2
방탄소년단     5        5       5         5       5      5      5       5
블랙핑크      4        4       4         4       4      4      4       4
소녀시대      2        2       2         2       1      2      2       2
워너원       2        1       2         2       2      2      2       2
콩         1        1       1         1       1      1      1       1

In [ ]:
df.groupby('group').mean(numeric_only=True)

       height      brand
group
뉴진스    166.04  3082933.2
레드벨벳   164.50  1786140.5
방탄소년단  178.40  3858656.0
블랙핑크   165.00  2024410.5
소녀시대   168.00  1982581.5
워너원    180.50  1830385.5
콩      140.00  1234567.0

In [ ]:
df.groupby('group').sum(numeric_only=True)

       height     brand
group
뉴진스     830.2  15414666
레드벨벳    329.0   3572281
방탄소년단   892.0  19293280
블랙핑크    660.0   8097642
소녀시대    168.0   3965163
워너원     361.0   3660771
콩       140.0   1234567

In [ ]:
df.groupby('gender').mean(numeric_only=True)

            height         brand
gender
남자      179.000000  3.279150e+06
여자      163.630769  2.306023e+06

In [ ]:
df.groupby('gender').mean(['height', 'brand'])

            height         brand
gender
남자      179.000000  3.279150e+06
여자      163.630769  2.306023e+06

### 문제
* 혈액형별로 그룹을 맺고, 성별로 또 그룹을 나눈 후 키의 평균갑에 대한 데이터를 출력

In [ ]:
df.groupby(['blood', 'gender'])['height'].mean()

blood  gender
A      남자        179.000000
       여자        161.166667
AB     남자        179.000000
B      여자        165.875000
O      남자        179.000000
       여자        165.850000
Name: height, dtype: float64

# **10. 중복값 제거하기**

In [ ]:
# drop_uplicates(): 중복된 데이터를 제거
df['blood'].drop_duplicates()

0      A
3      O
4     AB
5    NaN
8      B
Name: blood, dtype: object

In [ ]:
df['blood'].drop_duplicates(keep='last')

4      AB
5     NaN
15      B
19      O
20      A
Name: blood, dtype: object

In [ ]:
# value_counts(): 열의 각 값에 대한 데이터의 개수를 반환. NaN은 생략
df['blood'].value_counts()

blood
A     12
B      4
O      3
AB     1
Name: count, dtype: int64

In [ ]:
df['company'].value_counts()

company
빅히트     7
어도어     5
와이지     4
에스엠     2
판타지오    1
우유조아    1
Name: count, dtype: int64

In [ ]:
df['company'].value_counts(dropna=False)

company
빅히트     7
어도어     5
와이지     4
에스엠     2
판타지오    1
NaN     1
우유조아    1
Name: count, dtype: int64

# **11. 데이터프레임 합치기**

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/컴퓨터비전_시즌2/3. 데이터 분석/Data/idol.csv')
df2 = pd.read_csv('/content/drive/MyDrive/컴퓨터비전_시즌2/3. 데이터 분석/Data/idol2.csv')

In [ ]:
df1

      이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587

In [ ]:
df2

      이름    연봉  가족수
0     지민  3000    3
1     정국  3500    3
2     민지  3200    4
3     하니  3050    4
4      뷔  4300    3
5    다니엘  2900    5
6     혜인  3400    6
7     지수  4500    5
8     해린  4200    4
9     태연  4300    4
10    RM  3700    3
11    제니  3850    5
12   옹성우  3900    4
13    리사  4100    3
14    로제  4150    3
15    윤아  3000    3
16    조이  3500    3
17    슬기  3200    4
18  강다니엘  3050    4
19     진  4300    3

In [ ]:
df_copy = df1.copy()

In [ ]:
pd.concat([df1, df_copy]) # axis=0 (기본값)

      이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587

In [ ]:
# reset_index(): index를 새롭게 적용
df_concat = pd.concat([df1, df_copy])
df_concat.reset_index() # 기존의 인덱스가 index컬럼으로 추가됨

    index    이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수
0       0    지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
1       1    정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
2       2    민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
3       3    하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
4       4     뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
5       5   다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
6       6    혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
7       7    지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
8       8    해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
9       9    태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
10     10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
11     11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
12     12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
13     13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
14     14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
15     15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
16     16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
17     17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
18     18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
19     19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587
20      0    지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
21      1    정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
22      2    민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
23      3    하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
24      4     뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
25      5   다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
26      6    혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
27      7    지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
28      8    해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
29      9    태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
30     10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
31     11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
32     12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
33     13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
34     14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
35     15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
36     16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
37     17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
38     18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
39     19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587

In [ ]:
df_concat.reset_index(drop=True) # 기존의 인덱스 제거

      이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587
20    지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
21    정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
22    민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
23    하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
24     뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
25   다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
26    혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
27    지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
28    해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
29    태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
30    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
31    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
32   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
33    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
34    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
35    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
36    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
37    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
38  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
39     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587

In [ ]:
pd.concat([df1, df2], axis=1) # 같은 index끼리 결합

      이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수    이름    연봉  가족수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302    지민  3000    3
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844    정국  3500    3
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081    민지  3200    4
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153    하니  3050    4
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048     뷔  4300    3
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271   다니엘  2900    5
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785    혜인  3400    6
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460    지수  4500    5
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376    해린  4200    4
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866    태연  4300    4
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499    RM  3700    3
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250    제니  3850    5
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327   옹성우  3900    4
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800    리사  4100    3
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132    로제  4150    3
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297    윤아  3000    3
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514    조이  3500    3
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767    슬기  3200    4
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444  강다니엘  3050    4
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587     진  4300    3

In [ ]:
df3 = df2.drop([1, 3, 5, 7])
df3

      이름    연봉  가족수
0     지민  3000    3
2     민지  3200    4
4      뷔  4300    3
6     혜인  3400    6
8     해린  4200    4
9     태연  4300    4
10    RM  3700    3
11    제니  3850    5
12   옹성우  3900    4
13    리사  4100    3
14    로제  4150    3
15    윤아  3000    3
16    조이  3500    3
17    슬기  3200    4
18  강다니엘  3050    4
19     진  4300    3

In [ ]:
pd.concat([df1, df3], axis=1)

      이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수    이름      연봉  가족수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302    지민  3000.0  3.0
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844   NaN     NaN  NaN
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081    민지  3200.0  4.0
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153   NaN     NaN  NaN
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048     뷔  4300.0  3.0
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271   NaN     NaN  NaN
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785    혜인  3400.0  6.0
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460   NaN     NaN  NaN
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376    해린  4200.0  4.0
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866    태연  4300.0  4.0
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499    RM  3700.0  3.0
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250    제니  3850.0  5.0
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327   옹성우  3900.0  4.0
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800    리사  4100.0  3.0
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132    로제  4150.0  3.0
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297    윤아  3000.0  3.0
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514    조이  3500.0  3.0
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767    슬기  3200.0  4.0
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444  강다니엘  3050.0  4.0
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587     진  4300.0  3.0

In [ ]:
df_right = df2.drop([1, 3, 5, 7, 9], axis=0)
df_right

      이름    연봉  가족수
0     지민  3000    3
2     민지  3200    4
4      뷔  4300    3
6     혜인  3400    6
8     해린  4200    4
10    RM  3700    3
11    제니  3850    5
12   옹성우  3900    4
13    리사  4100    3
14    로제  4150    3
15    윤아  3000    3
16    조이  3500    3
17    슬기  3200    4
18  강다니엘  3050    4
19     진  4300    3

In [ ]:
# 1, 3, 5, 7, 9 행 제거 후 인덱스 리셋
df_right = df_right.reset_index(drop=True)
df_right

      이름    연봉  가족수
0     지민  3000    3
1     민지  3200    4
2      뷔  4300    3
3     혜인  3400    6
4     해린  4200    4
5     RM  3700    3
6     제니  3850    5
7    옹성우  3900    4
8     리사  4100    3
9     로제  4150    3
10    윤아  3000    3
11    조이  3500    3
12    슬기  3200    4
13  강다니엘  3050    4
14     진  4300    3

In [ ]:
dic = {
    '이름':'유민콩',
    '연봉':6000,
    '가족수':10
}

In [ ]:
df_right = pd.concat([df_right, pd.DataFrame(dic, index=[0])], ignore_index=True)
df_right

      이름    연봉  가족수
0     지민  3000    3
1     민지  3200    4
2      뷔  4300    3
3     혜인  3400    6
4     해린  4200    4
5     RM  3700    3
6     제니  3850    5
7    옹성우  3900    4
8     리사  4100    3
9     로제  4150    3
10    윤아  3000    3
11    조이  3500    3
12    슬기  3200    4
13  강다니엘  3050    4
14     진  4300    3
15   유민콩  6000   10

In [ ]:
# 합쳐보기
pd.concat([df1, df_right], axis=1)

      이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수    이름      연봉   가족수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302    지민  3000.0   3.0
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844    민지  3200.0   4.0
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081     뷔  4300.0   3.0
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153    혜인  3400.0   6.0
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048    해린  4200.0   4.0
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271    RM  3700.0   3.0
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785    제니  3850.0   5.0
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460   옹성우  3900.0   4.0
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376    리사  4100.0   3.0
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866    로제  4150.0   3.0
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499    윤아  3000.0   3.0
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250    조이  3500.0   3.0
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327    슬기  3200.0   4.0
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800  강다니엘  3050.0   4.0
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132     진  4300.0   3.0
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297   유민콩  6000.0  10.0
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514   NaN     NaN   NaN
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767   NaN     NaN   NaN
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444   NaN     NaN   NaN
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587   NaN     NaN   NaN

In [ ]:
# merge(): 특정 고유한 키(unique, id)값을 기준으로 합침
# merge(데이터프레임1, 데이터프레임2, on='유니크값', how='병합 기준')
# 병합의 기준: left, right, inner. cross
pd.merge(df1, df_right, on='이름', how='left') # 이름을 기준으로 합치고, 왼쪽의 데이터(df1)의 개수에 맞게 출력

      이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수      연봉  가족수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302  3000.0  3.0
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844     NaN  NaN
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081  3200.0  4.0
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153     NaN  NaN
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048  4300.0  3.0
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271     NaN  NaN
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785  3400.0  6.0
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460     NaN  NaN
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376  4200.0  4.0
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866     NaN  NaN
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499  3700.0  3.0
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250  3850.0  5.0
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327  3900.0  4.0
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800  4100.0  3.0
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132  4150.0  3.0
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297  3000.0  3.0
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514  3500.0  3.0
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767  3200.0  4.0
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444  3050.0  4.0
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587  4300.0  3.0

In [ ]:
pd.merge(df1, df_right, on='이름', how='right')

      이름     그룹   소속사   성별        생년월일      키  혈액형    브랜드평판지수    연봉  가족수
0     지민  방탄소년단   빅히트   남자  1995-10-13  174.0    A  6267302.0  3000    3
1     민지    뉴진스   어도어   여자  2004-05-07  169.0    A  4437081.0  3200    4
2      뷔  방탄소년단   빅히트   남자  1995-12-30  179.0   AB  3470048.0  4300    3
3     혜인    뉴진스   어도어   여자  2008-04-21  170.0    O  2301785.0  3400    6
4     해린    뉴진스   어도어   여자  2006-05-15  164.5    B  2173376.0  4200    4
5     RM  방탄소년단   빅히트   남자  1994-09-12  181.0    A  2069499.0  3700    3
6     제니   블랙핑크   와이지   여자  1996-01-16  163.0    B  2069250.0  3850    5
7    옹성우    워너원  판타지오   남자  1995-08-25  179.0    A  1954327.0  3900    4
8     리사   블랙핑크   와이지   여자  1997-03-27  167.0    A  1912800.0  4100    3
9     로제   블랙핑크   와이지   여자  1997-02-11  168.0    B  1888132.0  4150    3
10    윤아   소녀시대   에스엠   여자  1990-05-30  168.0    B  1885297.0  3000    3
11    조이   레드벨벳   빅히트   여자  1996-09-03  168.0    A  1830514.0  3500    3
12    슬기   레드벨벳   빅히트   여자  1994-02-10  161.0    A  1741767.0  3200    4
13  강다니엘    워너원   NaN   남자  1996-12-10  182.0    A  1706444.0  3050    4
14     진  방탄소년단   빅히트   남자  1992-12-04  179.0    O  1680587.0  4300    3
15   유민콩    NaN   NaN  NaN         NaN    NaN  NaN        NaN  6000   10

In [ ]:
pd.merge(df1, df_right, on='이름', how='inner') # 이름을 기준으로 교집합

      이름     그룹   소속사  성별        생년월일      키 혈액형  브랜드평판지수    연봉  가족수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0   A  6267302  3000    3
1     민지    뉴진스   어도어  여자  2004-05-07  169.0   A  4437081  3200    4
2      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0  AB  3470048  4300    3
3     혜인    뉴진스   어도어  여자  2008-04-21  170.0   O  2301785  3400    6
4     해린    뉴진스   어도어  여자  2006-05-15  164.5   B  2173376  4200    4
5     RM  방탄소년단   빅히트  남자  1994-09-12  181.0   A  2069499  3700    3
6     제니   블랙핑크   와이지  여자  1996-01-16  163.0   B  2069250  3850    5
7    옹성우    워너원  판타지오  남자  1995-08-25  179.0   A  1954327  3900    4
8     리사   블랙핑크   와이지  여자  1997-03-27  167.0   A  1912800  4100    3
9     로제   블랙핑크   와이지  여자  1997-02-11  168.0   B  1888132  4150    3
10    윤아   소녀시대   에스엠  여자  1990-05-30  168.0   B  1885297  3000    3
11    조이   레드벨벳   빅히트  여자  1996-09-03  168.0   A  1830514  3500    3
12    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0   A  1741767  3200    4
13  강다니엘    워너원   NaN  남자  1996-12-10  182.0   A  1706444  3050    4
14     진  방탄소년단   빅히트  남자  1992-12-04  179.0   O  1680587  4300    3

In [ ]:
pd.merge(df1, df_right, how='cross') # 모든 경우의 수

    이름_x     그룹  소속사  성별        생년월일      키 혈액형  브랜드평판지수  이름_y    연봉  가족수
0     지민  방탄소년단  빅히트  남자  1995-10-13  174.0   A  6267302    지민  3000    3
1     지민  방탄소년단  빅히트  남자  1995-10-13  174.0   A  6267302    민지  3200    4
2     지민  방탄소년단  빅히트  남자  1995-10-13  174.0   A  6267302     뷔  4300    3
3     지민  방탄소년단  빅히트  남자  1995-10-13  174.0   A  6267302    혜인  3400    6
4     지민  방탄소년단  빅히트  남자  1995-10-13  174.0   A  6267302    해린  4200    4
..   ...    ...  ...  ..         ...    ...  ..      ...   ...   ...  ...
315    진  방탄소년단  빅히트  남자  1992-12-04  179.0   O  1680587    조이  3500    3
316    진  방탄소년단  빅히트  남자  1992-12-04  179.0   O  1680587    슬기  3200    4
317    진  방탄소년단  빅히트  남자  1992-12-04  179.0   O  1680587  강다니엘  3050    4
318    진  방탄소년단  빅히트  남자  1992-12-04  179.0   O  1680587     진  4300    3
319    진  방탄소년단  빅히트  남자  1992-12-04  179.0   O  1680587   유민콩  6000   10

[320 rows x 11 columns]

In [ ]:
df_right.columns = ['성함', '연봉', '가족수']
df_right

      성함    연봉  가족수
0     지민  3000    3
1     민지  3200    4
2      뷔  4300    3
3     혜인  3400    6
4     해린  4200    4
5     RM  3700    3
6     제니  3850    5
7    옹성우  3900    4
8     리사  4100    3
9     로제  4150    3
10    윤아  3000    3
11    조이  3500    3
12    슬기  3200    4
13  강다니엘  3050    4
14     진  4300    3
15   유민콩  6000   10

In [ ]:
# pd.merge(df1, df_right, on='이름', how='right')
# KeyError: '이름'

In [ ]:
pd.merge(df1, df_right, left_on='이름', right_on='성함', how='right')

      이름     그룹   소속사   성별        생년월일      키  혈액형    브랜드평판지수    성함    연봉  가족수
0     지민  방탄소년단   빅히트   남자  1995-10-13  174.0    A  6267302.0    지민  3000    3
1     민지    뉴진스   어도어   여자  2004-05-07  169.0    A  4437081.0    민지  3200    4
2      뷔  방탄소년단   빅히트   남자  1995-12-30  179.0   AB  3470048.0     뷔  4300    3
3     혜인    뉴진스   어도어   여자  2008-04-21  170.0    O  2301785.0    혜인  3400    6
4     해린    뉴진스   어도어   여자  2006-05-15  164.5    B  2173376.0    해린  4200    4
5     RM  방탄소년단   빅히트   남자  1994-09-12  181.0    A  2069499.0    RM  3700    3
6     제니   블랙핑크   와이지   여자  1996-01-16  163.0    B  2069250.0    제니  3850    5
7    옹성우    워너원  판타지오   남자  1995-08-25  179.0    A  1954327.0   옹성우  3900    4
8     리사   블랙핑크   와이지   여자  1997-03-27  167.0    A  1912800.0    리사  4100    3
9     로제   블랙핑크   와이지   여자  1997-02-11  168.0    B  1888132.0    로제  4150    3
10    윤아   소녀시대   에스엠   여자  1990-05-30  168.0    B  1885297.0    윤아  3000    3
11    조이   레드벨벳   빅히트   여자  1996-09-03  168.0    A  1830514.0    조이  3500    3
12    슬기   레드벨벳   빅히트   여자  1994-02-10  161.0    A  1741767.0    슬기  3200    4
13  강다니엘    워너원   NaN   남자  1996-12-10  182.0    A  1706444.0  강다니엘  3050    4
14     진  방탄소년단   빅히트   남자  1992-12-04  179.0    O  1680587.0     진  4300    3
15   NaN    NaN   NaN  NaN         NaN    NaN  NaN        NaN   유민콩  6000   10

# **12. 등수 매기기**

In [ ]:
# rank(): 데이터프레임 또는 시리즈의 순위를 매기는 함수. 기본값은 ascending
df1['브랜드순위'] = df1['브랜드평판지수'].rank()
df1

      이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수  브랜드순위
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302   20.0
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844   19.0
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081   18.0
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153   17.0
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048   16.0
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271   15.0
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785   14.0
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460   13.0
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376   12.0
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866   11.0
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499   10.0
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250    9.0
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327    8.0
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800    7.0
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132    6.0
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297    5.0
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514    4.0
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767    3.0
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444    2.0
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587    1.0

In [ ]:
df1['브랜드순위'] = df1['브랜드평판지수'].rank(ascending=False)
df1

      이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수  브랜드순위
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302    1.0
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844    2.0
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081    3.0
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153    4.0
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048    5.0
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271    6.0
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785    7.0
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460    8.0
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376    9.0
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866   10.0
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499   11.0
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250   12.0
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327   13.0
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800   14.0
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132   15.0
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297   16.0
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514   17.0
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767   18.0
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444   19.0
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587   20.0

In [ ]:
# astype(): 특정열의 자료형을 변경
df1['브랜드순위'] = df1['브랜드평판지수'].rank(ascending=False).astype('int')
df1

      이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수  브랜드순위
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302      1
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844      2
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081      3
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153      4
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048      5
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271      6
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785      7
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460      8
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376      9
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866     10
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499     11
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250     12
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327     13
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800     14
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132     15
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297     16
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514     17
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767     18
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444     19
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587     20

# **13. 날짜 타입 사용하기**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      21 non-null     object
 1   group     21 non-null     object
 2   company   20 non-null     object
 3   gender    21 non-null     object
 4   birthday  21 non-null     object
 5   height    20 non-null     float64
 6   blood     20 non-null     object
 7   brand     21 non-null     int64
 8   nation    21 non-null     object
dtypes: float64(1), int64(1), object(7)
memory usage: 1.6+ KB

In [ ]:
df['birthday']

0     1995-10-13
1     1997-09-01
2     2004-05-07
3     2004-10-06
4     1995-12-30
5     2005-04-11
6     2008-04-21
7     1995-01-03
8     2006-05-15
9     1989-03-09
10    1994-09-12
11    1996-01-16
12    1995-08-25
13    1997-03-27
14    1997-02-11
15    1990-05-30
16    1996-09-03
17    1994-02-10
18    1996-12-10
19    1992-12-04
20    2020-02-02
Name: birthday, dtype: object

In [ ]:
# to_datetime(): object타입에서 datetime타입으로 변경
df['birthday'] = pd.to_datetime(df['birthday'])
df['birthday']

0    1995-10-13
1    1997-09-01
2    2004-05-07
3    2004-10-06
4    1995-12-30
5    2005-04-11
6    2008-04-21
7    1995-01-03
8    2006-05-15
9    1989-03-09
10   1994-09-12
11   1996-01-16
12   1995-08-25
13   1997-03-27
14   1997-02-11
15   1990-05-30
16   1996-09-03
17   1994-02-10
18   1996-12-10
19   1992-12-04
20   2020-02-02
Name: birthday, dtype: datetime64[ns]

In [ ]:
print(type(df['birthday']))
print(df['birthday'].dtypes)

<class 'pandas.core.series.Series'>
datetime64[ns]

In [ ]:
df['birthday'].dt.year # 연도만 출력

0     1995
1     1997
2     2004
3     2004
4     1995
5     2005
6     2008
7     1995
8     2006
9     1989
10    1994
11    1996
12    1995
13    1997
14    1997
15    1990
16    1996
17    1994
18    1996
19    1992
20    2020
Name: birthday, dtype: int32

In [ ]:
df['birthday'].dt.month # 월만 출력

0     10
1      9
2      5
3     10
4     12
5      4
6      4
7      1
8      5
9      3
10     9
11     1
12     8
13     3
14     2
15     5
16     9
17     2
18    12
19    12
20     2
Name: birthday, dtype: int32

In [ ]:
df['birthday'].dt.day # 일만 출력

0     13
1      1
2      7
3      6
4     30
5     11
6     21
7      3
8     15
9      9
10    12
11    16
12    25
13    27
14    11
15    30
16     3
17    10
18    10
19     4
20     2
Name: birthday, dtype: int32

In [ ]:
df['birthday'].dt.hour # 시간만 출력

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
Name: birthday, dtype: int32

In [ ]:
df['birthday'].dt.minute # 분만 출력

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
Name: birthday, dtype: int32

In [ ]:
df['birthday'].dt.second # 초만 출력

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
Name: birthday, dtype: int32

In [ ]:
df['birthday'].dt.dayofweek # 요일(0:월, 6:일)

0     4
1     0
2     4
3     2
4     5
5     0
6     0
7     1
8     0
9     3
10    0
11    1
12    4
13    3
14    1
15    2
16    1
17    3
18    1
19    4
20    6
Name: birthday, dtype: int32

In [ ]:
df['birthday'].dt.isocalendar().week # 주차

0     41
1     36
2     19
3     41
4     52
5     15
6     17
7      1
8     20
9     10
10    37
11     3
12    34
13    13
14     7
15    22
16    36
17     6
18    50
19    49
20     5
Name: week, dtype: UInt32

# **14. apply 사용하기**
* Series나 DataFrame에 구체적인 로직을 적용하고 싶을 때 사용
* apply를 적용하기 위해서는 별도의 함수를 먼저 정의해야 함
* 작성된 함수를 apply에 매개변수로 전달함
* 콜백함수

In [ ]:
df.head()

  name  group company gender   birthday  height blood    brand nation
0   지민  방탄소년단     빅히트     남자 1995-10-13   174.0     A  6267302   대한민국
1   정국  방탄소년단     빅히트     남자 1997-09-01   179.0     A  5805844   대한민국
2   민지    뉴진스     어도어     여자 2004-05-07   169.0     A  4437081   대한민국
3   하니    뉴진스     어도어     여자 2004-10-06   161.7     O  4161153   대한민국
4    뷔  방탄소년단     빅히트     남자 1995-12-30   179.0    AB  3470048   대한민국

In [ ]:
# 성별을 남자는 1 여자는 0으로 변환(loc 사용)
df.loc[df['gender'] == '남자', 'gender'] = 1
df.loc[df['gender'] == '여자', 'gender'] = 0
df.head()

  name  group company gender   birthday  height blood    brand nation
0   지민  방탄소년단     빅히트      1 1995-10-13   174.0     A  6267302   대한민국
1   정국  방탄소년단     빅히트      1 1997-09-01   179.0     A  5805844   대한민국
2   민지    뉴진스     어도어      0 2004-05-07   169.0     A  4437081   대한민국
3   하니    뉴진스     어도어      0 2004-10-06   161.7     O  4161153   대한민국
4    뷔  방탄소년단     빅히트      1 1995-12-30   179.0    AB  3470048   대한민국

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/컴퓨터비전_시즌2/3. 데이터 분석/Data/idol.csv')
df

      이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587

In [ ]:
def male_or_female(x):
  if x == '남자':
    return 1
  elif x == '여자':
    return 0
  else:
    return None

In [ ]:
df['성별'].apply(male_or_female) # 모든 행에 함수 적용됨

0     1
1     1
2     0
3     0
4     1
5     0
6     0
7     0
8     0
9     0
10    1
11    0
12    1
13    0
14    0
15    0
16    0
17    0
18    1
19    1
Name: 성별, dtype: int64

In [ ]:
# 람다형으로
df['성별'].apply(lambda x: 1 if x == '남자' else 0)

0     1
1     1
2     0
3     0
4     1
5     0
6     0
7     0
8     0
9     0
10    1
11    0
12    1
13    0
14    0
15    0
16    0
17    0
18    1
19    1
Name: 성별, dtype: int64

In [ ]:
df['new성별'] = df['성별'].apply(lambda x: 1 if x == '남자' else 0) # 파생변수로 추가
df.head()

   이름     그룹  소속사  성별        생년월일      키 혈액형  브랜드평판지수  new성별
0  지민  방탄소년단  빅히트  남자  1995-10-13  174.0   A  6267302      1
1  정국  방탄소년단  빅히트  남자  1997-09-01  179.0   A  5805844      1
2  민지    뉴진스  어도어  여자  2004-05-07  169.0   A  4437081      0
3  하니    뉴진스  어도어  여자  2004-10-06  161.7   O  4161153      0
4   뷔  방탄소년단  빅히트  남자  1995-12-30  179.0  AB  3470048      1

# **15. map 사용하기**
* 딕셔너리를 통해 데이터와 같은 키의 값을 적용

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/컴퓨터비전_시즌2/3. 데이터 분석/Data/idol.csv')
df

      이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587

In [ ]:
map_gender = {
    '남자':1,
    '여자':0
}

In [ ]:
df['성별'].map(map_gender)

0     1
1     1
2     0
3     0
4     1
5     0
6     0
7     0
8     0
9     0
10    1
11    0
12    1
13    0
14    0
15    0
16    0
17    0
18    1
19    1
Name: 성별, dtype: int64

In [ ]:
df['new성별'] = df['성별'].map(map_gender)
df

      이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수  new성별
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302      1
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844      1
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081      0
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153      0
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048      1
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271      0
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785      0
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460      0
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376      0
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866      0
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499      1
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250      0
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327      1
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800      0
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132      0
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297      0
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514      0
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767      0
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444      1
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587      1

# **16. 데이터프레임의 산술연산**

In [ ]:
df = pd.DataFrame({
    '파이썬':[60, 70, 80, 90, 95],
    '데이터분석':[40, 60, 70, 55, 87],
    '머신러닝딥러닝':[35, 40, 30, 70, 55]
})

In [ ]:
df

   파이썬  데이터분석  머신러닝딥러닝
0   60     40       35
1   70     60       40
2   80     70       30
3   90     55       70
4   95     87       55

In [ ]:
print(df['파이썬'].dtypes)
print(type(df['파이썬']))

int64
<class 'pandas.core.series.Series'>

In [ ]:
df['파이썬'] + df['데이터분석'] + df['머신러닝딥러닝']

0    135
1    170
2    180
3    215
4    237
dtype: int64

In [ ]:
# df에 총점, 평균이라는 파생변수를 만들고 파생변수에 총점, 평균을 구해서 저장
df['총점'] = df['파이썬'] + df['데이터분석'] + df['머신러닝딥러닝']
df['평균'] = df['총점'] / 3
df

   파이썬  데이터분석  머신러닝딥러닝   총점         평균
0   60     40       35  135  45.000000
1   70     60       40  170  56.666667
2   80     70       30  180  60.000000
3   90     55       70  215  71.666667
4   95     87       55  237  79.000000

In [ ]:
df['파이썬'].sum() # df['파이썬'].sum(axis=0)

395

In [ ]:
df['파이썬'].mean() # df['파이썬'].mean(axis=0)

79.0

In [ ]:
df.sum()

파이썬        395.000000
데이터분석      312.000000
머신러닝딥러닝    230.000000
총점         937.000000
평균         312.333333
dtype: float64

In [ ]:
df.mean()

파이썬         79.000000
데이터분석       62.400000
머신러닝딥러닝     46.000000
총점         187.400000
평균          62.466667
dtype: float64

In [ ]:
df1 = pd.DataFrame({
    '파이썬':[60, 70, 80, 90, 95],
    '데이터분석':[40, 60, 70, 55, 87],
    '머신러닝딥러닝':[35, 40, 30, 70, 55]
})

df2 = pd.DataFrame({
    '파이썬':['C', 'B', 'B', 'A', 'A'],
    '데이터분석':[40, 60, 70, 55, 87],
    '머신러닝딥러닝':[35, 40, 30, 70, 55]
})

In [ ]:
# df1 + df2
# TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
df1 + 10

   파이썬  데이터분석  머신러닝딥러닝
0   70     50       45
1   80     70       50
2   90     80       40
3  100     65       80
4  105     97       65

In [ ]:
# df2 + 10
# TypeError: can only concatenate str (not "int") to str

In [ ]:
df1 = pd.DataFrame({
    '데이터분석':[40, 60, 70, 55, 87],
    '머신러닝딥러닝':[35, 40, 30, 70, 55]
})

df2 = pd.DataFrame({
    '데이터분석':[40, 60, 70, 55],
    '머신러닝딥러닝':[35, 40, 30, 70]
})

In [ ]:
df1 + df2 # 행의 개수가 빠진 경우 데이터를 nan으로 취급하기 때문에 결과도 nan
# 파이썬은 nan과 더하면 무조건 nan

   데이터분석  머신러닝딥러닝
0   80.0     70.0
1  120.0     80.0
2  140.0     60.0
3  110.0    140.0
4    NaN      NaN

# **17. select_dtypes**

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/컴퓨터비전_시즌2/3. 데이터 분석/Data/idol.csv')
df

      이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   이름       20 non-null     object
 1   그룹       20 non-null     object
 2   소속사      19 non-null     object
 3   성별       20 non-null     object
 4   생년월일     20 non-null     object
 5   키        19 non-null     float64
 6   혈액형      19 non-null     object
 7   브랜드평판지수  20 non-null     int64
dtypes: float64(1), int64(1), object(6)
memory usage: 1.4+ KB

In [ ]:
df.select_dtypes(include='object') # 문자열 컬럼만 가져오기

      이름     그룹   소속사  성별        생년월일  혈액형
0     지민  방탄소년단   빅히트  남자  1995-10-13    A
1     정국  방탄소년단   빅히트  남자  1997-09-01    A
2     민지    뉴진스   어도어  여자  2004-05-07    A
3     하니    뉴진스   어도어  여자  2004-10-06    O
4      뷔  방탄소년단   빅히트  남자  1995-12-30   AB
5    다니엘    뉴진스   어도어  여자  2005-04-11  NaN
6     혜인    뉴진스   어도어  여자  2008-04-21    O
7     지수   블랙핑크   와이지  여자  1995-01-03    A
8     해린    뉴진스   어도어  여자  2006-05-15    B
9     태연   소녀시대   에스엠  여자  1989-03-09    A
10    RM  방탄소년단   빅히트  남자  1994-09-12    A
11    제니   블랙핑크   와이지  여자  1996-01-16    B
12   옹성우    워너원  판타지오  남자  1995-08-25    A
13    리사   블랙핑크   와이지  여자  1997-03-27    A
14    로제   블랙핑크   와이지  여자  1997-02-11    B
15    윤아   소녀시대   에스엠  여자  1990-05-30    B
16    조이   레드벨벳   빅히트  여자  1996-09-03    A
17    슬기   레드벨벳   빅히트  여자  1994-02-10    A
18  강다니엘    워너원   NaN  남자  1996-12-10    A
19     진  방탄소년단   빅히트  남자  1992-12-04    O

In [ ]:
df.select_dtypes(exclude='object') # 문자열 컬럼만 빼고 가져오기

        키  브랜드평판지수
0   174.0  6267302
1   179.0  5805844
2   169.0  4437081
3   161.7  4161153
4   179.0  3470048
5   165.0  2341271
6   170.0  2301785
7   162.0  2227460
8   164.5  2173376
9     NaN  2079866
10  181.0  2069499
11  163.0  2069250
12  179.0  1954327
13  167.0  1912800
14  168.0  1888132
15  168.0  1885297
16  168.0  1830514
17  161.0  1741767
18  182.0  1706444
19  179.0  1680587

In [ ]:
# 문자가 아닌 컬럼에만 10을 더함
df.select_dtypes(exclude='object')+10

        키  브랜드평판지수
0   184.0  6267312
1   189.0  5805854
2   179.0  4437091
3   171.7  4161163
4   189.0  3470058
5   175.0  2341281
6   180.0  2301795
7   172.0  2227470
8   174.5  2173386
9     NaN  2079876
10  191.0  2069509
11  173.0  2069260
12  189.0  1954337
13  177.0  1912810
14  178.0  1888142
15  178.0  1885307
16  178.0  1830524
17  171.0  1741777
18  192.0  1706454
19  189.0  1680597

In [ ]:
# 문자열을 가지고 있는 컬럼의 이름만 변수에 저장하여 출력

In [ ]:
object_names = df.select_dtypes(include=object).columns
object_names

Index(['이름', '그룹', '소속사', '성별', '생년월일', '혈액형'], dtype='object')

In [ ]:
df[object_names]

      이름     그룹   소속사  성별        생년월일  혈액형
0     지민  방탄소년단   빅히트  남자  1995-10-13    A
1     정국  방탄소년단   빅히트  남자  1997-09-01    A
2     민지    뉴진스   어도어  여자  2004-05-07    A
3     하니    뉴진스   어도어  여자  2004-10-06    O
4      뷔  방탄소년단   빅히트  남자  1995-12-30   AB
5    다니엘    뉴진스   어도어  여자  2005-04-11  NaN
6     혜인    뉴진스   어도어  여자  2008-04-21    O
7     지수   블랙핑크   와이지  여자  1995-01-03    A
8     해린    뉴진스   어도어  여자  2006-05-15    B
9     태연   소녀시대   에스엠  여자  1989-03-09    A
10    RM  방탄소년단   빅히트  남자  1994-09-12    A
11    제니   블랙핑크   와이지  여자  1996-01-16    B
12   옹성우    워너원  판타지오  남자  1995-08-25    A
13    리사   블랙핑크   와이지  여자  1997-03-27    A
14    로제   블랙핑크   와이지  여자  1997-02-11    B
15    윤아   소녀시대   에스엠  여자  1990-05-30    B
16    조이   레드벨벳   빅히트  여자  1996-09-03    A
17    슬기   레드벨벳   빅히트  여자  1994-02-10    A
18  강다니엘    워너원   NaN  남자  1996-12-10    A
19     진  방탄소년단   빅히트  남자  1992-12-04    O

# **18. 원 핫 인코딩(One Hot Encoding)**
* 원 핫 인코딩은 한개의 요소는 1, 나머지 요소는 0으로 만들어 카테고리형을 표현하는 방법
* 예: df['혈액형']
  * 머신러닝/딥러닝 알고리즘에 넣어 데이터를 예측하려고 한다면 라벨 인코딩을 하여 수치 데이터로 변환
  * 컴퓨터는 값의 관계를 스스로 형성하게 될 수 있음
  * 만약 B형을1. AB형이 2라는 값을 가지고 있다면. 컴퓨터는 'B형 + AB형 = O형'이라는 이상한 관계를 맺을 수 있음
  * 따라서 별도의 column들을 형성해주고 1개의 column에는 1, 나머지 column에는 0으로 넣어줌으로 'A, B, AB, O형의 관계는 서로 독립적이다'라는 카테고리로 표현하는 방식

In [ ]:
blood_map = {'A':0, 'B':1, 'AB':2, 'O':3}
df['혈액형_code'] = df['혈액형'].map(blood_map) # 라벨 인코딩
df.head()

   이름     그룹  소속사  성별        생년월일      키 혈액형  브랜드평판지수  혈액형_code
0  지민  방탄소년단  빅히트  남자  1995-10-13  174.0   A  6267302       0.0
1  정국  방탄소년단  빅히트  남자  1997-09-01  179.0   A  5805844       0.0
2  민지    뉴진스  어도어  여자  2004-05-07  169.0   A  4437081       0.0
3  하니    뉴진스  어도어  여자  2004-10-06  161.7   O  4161153       3.0
4   뷔  방탄소년단  빅히트  남자  1995-12-30  179.0  AB  3470048       2.0

In [ ]:
pd.get_dummies(df['혈액형_code'])

      0.0    1.0    2.0    3.0
0    True  False  False  False
1    True  False  False  False
2    True  False  False  False
3   False  False  False   True
4   False  False   True  False
5   False  False  False  False
6   False  False  False   True
7    True  False  False  False
8   False   True  False  False
9    True  False  False  False
10   True  False  False  False
11  False   True  False  False
12   True  False  False  False
13   True  False  False  False
14  False   True  False  False
15  False   True  False  False
16   True  False  False  False
17   True  False  False  False
18   True  False  False  False
19  False  False  False   True

In [ ]:
pd.get_dummies(df['혈액형'])

        A     AB      B      O
0    True  False  False  False
1    True  False  False  False
2    True  False  False  False
3   False  False  False   True
4   False   True  False  False
5   False  False  False  False
6   False  False  False   True
7    True  False  False  False
8   False  False   True  False
9    True  False  False  False
10   True  False  False  False
11  False  False   True  False
12   True  False  False  False
13   True  False  False  False
14  False  False   True  False
15  False  False   True  False
16   True  False  False  False
17   True  False  False  False
18   True  False  False  False
19  False  False  False   True

In [ ]:
df = pd.get_dummies(df, columns=['혈액형'])
df

,이름,그룹,소속사,성별,생년월일,키,브랜드평판지수,혈액형_code,혈액형_A,혈액형_AB,혈액형_B,혈액형_O
0,지민,방탄소년단,빅히트,남자,1995-10-13,174.0,6267302,0.0,True,False,False,False
1,정국,방탄소년단,빅히트,남자,1997-09-01,179.0,5805844,0.0,True,False,False,False
2,민지,뉴진스,어도어,여자,2004-05-07,169.0,4437081,0.0,True,False,False,False
3,하니,뉴진스,어도어,여자,2004-10-06,161.7,4161153,3.0,False,False,False,True
4,뷔,방탄소년단,빅히트,남자,1995-12-30,179.0,3470048,2.0,False,True,False,False
5,다니엘,뉴진스,어도어,여자,2005-04-11,165.0,2341271,NaN,False,False,False,False
6,혜인,뉴진스,어도어,여자,2008-04-21,170.0,2301785,3.0,False,False,False,True
7,지수,블랙핑크,와이지,여자,1995-01-03,162.0,2227460,0.0,True,False,False,False
8,해린,뉴진스,어도어,여자,2006-05-15,164.5,2173376,1.0,False,False,True,False
9,태연,소녀시대,에스엠,여자,1989-03-09,NaN,2079866,0.0,True,False,False,False
10,RM,방탄소년단,빅히트,남자,1994-09-12,181.0,2069499,0.0,True,False,False,False
11,제니,블랙핑크,와이지,여자,1996-01-16,163.0,2069250,1.0,False,False,True,False
12,옹성우,워너원,판타지오,남자,1995-08-25,179.0,1954327,0.0,True,False,False,False
13,리사,블랙핑크,와이지,여자,1997-03-27,167.0,1912800,0.0,True,False,False,False
14,로제,블랙핑크,와이지,여자,1997-02-11,168.0,1888132,1.0,False,False,True,False
15,윤아,소녀시대,에스엠,여자,1990-05-30,168.0,1885297,1.0,False,False,True,False
16,조이,레드벨벳,빅히트,여자,1996-09-03,168.0,1830514,0.0,True,False,False,False
17,슬기,레드벨벳,빅히트,여자,1994-02-10,161.0,1741767,0.0,True,False,False,False
18,강다니엘,워너원,NaN,남자,1996-12-10,182.0,1706444,0.0,True,False,False,False
19,진,방탄소년단,빅히트,남자,1992-12-04,179.0,1680587,3.0,False,False,False,True